// githubfinder_react/src/Profile.js
import React, { Fragment } from "react";

const Profile = ({ user }) => (
  <Fragment>
    <div className="row">
      <div className="col-md-4">
        <div className="card" style={{ width: "18rem" }}>
          <img
            className="card-img-top"
            src={user.avatar_url}
            alt="Card image cap"
          />
          <ul className="list-group list-group-flush">
            <li className="list-group-item">
              Repositórios:{" "}
              <span className="badge badge-success float-right">
                {user.public_repos}
              </span>
            </li>
            <li className="list-group-item">
              Seguidores:{" "}
              <span className="badge badge-primary float-right">
                {user.followers}
              </span>
            </li>
            <li className="list-group-item">
              Seguindo:
              <span className="badge badge-info float-right">
                {user.following}
              </span>
            </li>
          </ul>
          <div className="card-body">
            <a
              href={user.html_url}
              target="_blank"
              className="btn btn-info btn-block">
              Ver Perfil
            </a>
          </div>
        </div>
      </div>
    </div>
  </Fragment>
);

export default Profile;

// githubfinder_vue/src/components/Profile.vue
<template>
  <div>
    <div class="row">
      <div class="col-md-4">
        <div
          class="card"
          style="width: 18rem;"
        >
          <img
            class="card-img-top"
            :src="user.avatar_url"
            alt="Card image cap"
          >
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Repositórios: <span class="badge badge-success float-right">{{user.public_repos}}</span></li>
            <li class="list-group-item">Seguidores: <span class="badge badge-primary float-right">{{user.followers}}</span></li>
            <li class="list-group-item">Seguindo:<span class="badge badge-info float-right">{{user.following}}</span></li>
          </ul>
          <div class="card-body">
            <a
              :href="user.html_url"
              target="_blank"
              class="btn btn-success btn-block"
            >Ver Perfil</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ["user"]
};
</script>
